import { Briefcase, Mail, User } from "lucide-react";
import TextField from "@/components/ui/TextField";
import type { SupervisorFieldValues } from "../hooks/use-supervisor-fields";

interface SupervisorFieldsProps {
  values: SupervisorFieldValues;
  setField: (
    key: keyof SupervisorFieldValues,
  ) => (e: { target: { value: string } }) => void;
  /**
   * Native `required` on first name, last name and email. Off on the
   * establishment create form, where the whole section is optional and the
   * hook checks it is either empty or complete.
   */
  required: boolean;
}

/**
 * The supervisor's five fields: on the establishment create form and in the
 * list's "Add supervisor" dialog. No username or password — both are
 * generated by the server and shown once.
 */
export default function SupervisorFields({
  values,
  setField,
  required,
}: SupervisorFieldsProps) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-3 md:gap-4">
      <TextField
        label="First Name"
        labelIcon={User}
        required={required}
        value={values.firstName}
        onChange={setField("firstName")}
        placeholder="Juan"
        maxLength={120}
      />
      <TextField
        label="Middle Initial"
        labelIcon={User}
        value={values.middleInitial}
        onChange={setField("middleInitial")}
        placeholder="P"
        maxLength={10}
      />
      <TextField
        label="Last Name"
        labelIcon={User}
        required={required}
        value={values.lastName}
        onChange={setField("lastName")}
        placeholder="Dela Cruz"
        maxLength={120}
      />
      <TextField
        label="Email"
        labelIcon={Mail}
        fieldIcon={Mail}
        type="email"
        required={required}
        value={values.email}
        onChange={setField("email")}
        placeholder="supervisor@company.com"
      />
      <TextField
        label="Position"
        labelIcon={Briefcase}
        fieldIcon={Briefcase}
        value={values.position}
        onChange={setField("position")}
        placeholder="HR Manager"
        maxLength={120}
      />
    </div>
  );
}
