import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQueryWithAuth } from "./baseQuery";
import type {
  GeneratedCredentials,
  ResendCredentialsResponse,
} from "./studentApi";
import { dashboardApi } from "./dashboardApi";
import { evaluationApi } from "./evaluationApi";
import { messagesApi } from "./messagesApi";

/**
 * The coordinator's view of supervisors (`/coordinator/supervisors`).
 *
 * Not to be confused with `supervisorApi.ts`, which serves a signed-in
 * supervisor their own approval queue and dashboard.
 */
export interface CoordinatorSupervisor {
  id: string;
  userId: string;
  establishmentId: string;
  position?: string | null;
  user: {
    id: string;
    email: string;
    username: string | null;
    name: string;
    createdAt: string;
  };
  establishment?: { id: string; name: string } | null;
  /**
   * What deleting this supervisor would destroy (`evaluations`) versus merely
   * un-attribute (`approvedPunches` — the punches they approved are kept and
   * only lose their decider). The delete confirmation states both.
   */
  _count?: { evaluations: number; approvedPunches: number } | null;
}

/**
 * No `username` or `password` — generated by the server and returned once in
 * `credentials`. The name comes in parts because the username is built from
 * the first initial and the last name.
 */
export interface CreateSupervisorRequest {
  email: string;
  firstName: string;
  middleInitial?: string;
  lastName: string;
  establishmentId: string;
  position?: string;
}

export interface CreateSupervisorResponse {
  id: string;
  email: string;
  username: string | null;
  name: string;
  role: string;
  credentials: GeneratedCredentials;
}

export const supervisorManagementApi = createApi({
  reducerPath: "supervisorManagementApi",
  baseQuery: baseQueryWithAuth,
  tagTypes: ["CoordinatorSupervisor"],
  endpoints: (builder) => ({
    getSupervisors: builder.query<CoordinatorSupervisor[], void>({
      query: () => "/coordinator/supervisors",
      providesTags: ["CoordinatorSupervisor"],
    }),
    createSupervisor: builder.mutation<
      CreateSupervisorResponse,
      CreateSupervisorRequest
    >({
      query: (body) => ({
        url: "/coordinator/supervisors",
        method: "POST",
        body,
      }),
      invalidatesTags: ["CoordinatorSupervisor"],
    }),
    /**
     * "Resend login": a new generated temporary password and a forced change
     * at next sign-in. Invalidates nothing — the supervisor list shows neither
     * the password nor the flag, and the username never changes.
     */
    resendSupervisorCredentials: builder.mutation<
      ResendCredentialsResponse,
      string
    >({
      query: (id) => ({
        url: `/coordinator/supervisors/${id}/resend-credentials`,
        method: "POST",
      }),
    }),
    deleteSupervisor: builder.mutation<{ id: string; deleted: boolean }, string>(
      {
        query: (id) => ({
          url: `/coordinator/supervisors/${id}`,
          method: "DELETE",
        }),
        invalidatesTags: ["CoordinatorSupervisor"],
        // deleteSupervisorCascade takes the supervisor's evaluations and
        // messages with it (attendance they approved is kept, just
        // un-attributed — attendanceOversightApi and documentApi show
        // nothing derived from the approver, so they don't need a nudge
        // here). See CLAUDE.md §8 item 22.
        async onQueryStarted(_id, { dispatch, queryFulfilled }) {
          try {
            await queryFulfilled;
            dispatch(dashboardApi.util.invalidateTags(["Dashboard"]));
            dispatch(evaluationApi.util.invalidateTags(["Evaluation"]));
            dispatch(
              messagesApi.util.invalidateTags(["Conversations", "Contacts"]),
            );
          } catch {
            // Delete failed — nothing else to invalidate.
          }
        },
      },
    ),
  }),
});

export const {
  useGetSupervisorsQuery,
  useCreateSupervisorMutation,
  useResendSupervisorCredentialsMutation,
  useDeleteSupervisorMutation,
} = supervisorManagementApi;
