import { useMemo, useState } from "react";
import {
  useGetSupervisorsQuery,
  useUpdateSupervisorMutation,
  useDeleteSupervisorMutation,
  useResendSupervisorCredentialsMutation,
  CoordinatorSupervisor,
} from "@/lib/api/supervisorManagementApi";
import type { IssuedCredentials } from "@/features/account/CredentialsDialog";
import { useSnackbar } from "@/lib/contexts/SnackbarContext";

// Edit only: supervisors are created inside an establishment (the
// Establishments page). No username (generated once, never changed), no
// password (Resend login) and no establishment (a supervisor stays where they
// were created).
const EMPTY_FORM = {
  email: "",
  firstName: "",
  middleInitial: "",
  lastName: "",
  position: "",
};

export type SupervisorForm = typeof EMPTY_FORM;

const PAGE_SIZE = 5;

export function useSupervisorManagement() {
  const [form, setForm] = useState<SupervisorForm>(EMPTY_FORM);
  const [error, setError] = useState("");
  /** The supervisor whose Resend login is awaiting confirmation. */
  const [resendTarget, setResendTarget] =
    useState<CoordinatorSupervisor | null>(null);
  /**
   * Login details just generated by Resend login, shown once. Cleared on
   * close and kept nowhere else, so nothing can reopen it.
   */
  const [issuedCredentials, setIssuedCredentials] =
    useState<IssuedCredentials | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<CoordinatorSupervisor | null>(
    null,
  );
  /** The supervisor being edited; `null` = the edit dialog is closed. */
  const [editTarget, setEditTarget] = useState<CoordinatorSupervisor | null>(
    null,
  );
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);

  const { showSuccess, showError } = useSnackbar();

  const { data: supervisors, isLoading } = useGetSupervisorsQuery();
  const [updateSupervisor, { isLoading: isSaving }] =
    useUpdateSupervisorMutation();
  const [deleteSupervisor] = useDeleteSupervisorMutation();
  const [resendCredentials, { isLoading: isResending }] =
    useResendSupervisorCredentialsMutation();

  const setField =
    (key: keyof SupervisorForm) =>
    (e: { target: { value: string } }) => {
      setForm((f) => ({ ...f, [key]: e.target.value }));
    };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editTarget) return;
    setError("");

    try {
      // Every field is sent: the server stores the name whole and rebuilds it
      // from the parts, and `null` clears the optional ones.
      await updateSupervisor({
        id: editTarget.id,
        firstName: form.firstName.trim(),
        middleInitial: form.middleInitial.trim() || null,
        lastName: form.lastName.trim(),
        email: form.email.trim(),
        position: form.position.trim() || null,
      }).unwrap();
      showSuccess(`"${editTarget.user.name}" has been updated.`);
      closeDialog();
    } catch (err: unknown) {
      const message = readError(err, "Failed to update supervisor.");
      setError(message);
      showError(message);
    }
  };

  const handleDeleteConfirm = async () => {
    if (!deleteTarget) return;
    try {
      await deleteSupervisor(deleteTarget.id).unwrap();
      showSuccess(`"${deleteTarget.user.name}" has been removed.`);
      setDeleteTarget(null);
    } catch (err: unknown) {
      const message = readError(err, "Failed to remove supervisor.");
      showError(message);
    }
  };

  /** Resend login: a new generated password, after the coordinator confirms. */
  const handleResendConfirm = async () => {
    if (!resendTarget) return;
    try {
      const result = await resendCredentials(resendTarget.id).unwrap();
      setResendTarget(null);
      setIssuedCredentials({
        name: result.name,
        email: result.email,
        username: result.credentials.username,
        tempPassword: result.credentials.tempPassword,
        reason: "resent",
      });
    } catch (err: unknown) {
      showError(readError(err, "Failed to issue a new login."));
    }
  };

  /**
   * Opens the edit dialog. Only `User.name` is stored, so the parts are a
   * best-effort split (`splitPersonName`) for the coordinator to check before
   * saving — the server rebuilds the name from whatever is saved.
   */
  const handleOpenEdit = (supervisor: CoordinatorSupervisor) => {
    setForm({
      ...splitPersonName(supervisor.user.name),
      email: supervisor.user.email,
      position: supervisor.position ?? "",
    });
    setError("");
    setEditTarget(supervisor);
  };

  const closeDialog = () => {
    setEditTarget(null);
    setForm(EMPTY_FORM);
    setError("");
  };

  const filtered = useMemo(() => {
    const term = search.toLowerCase();
    return (supervisors ?? []).filter((s) => {
      const haystack = [
        s.user.name,
        s.user.username,
        s.user.email,
        s.position,
        s.establishment?.name,
      ]
        .filter(Boolean)
        .join(" ")
        .toLowerCase();
      return haystack.includes(term);
    });
  }, [supervisors, search]);

  const totalPages = Math.ceil(filtered.length / PAGE_SIZE);
  const paged = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  const stats = useMemo(() => {
    const all = supervisors ?? [];
    return {
      total: all.length,
      establishmentsCovered: new Set(all.map((s) => s.establishmentId)).size,
      withoutPosition: all.filter((s) => !s.position).length,
    };
  }, [supervisors]);

  return {
    form,
    error,
    isLoading,
    isSaving,
    editTarget,
    resendTarget,
    isResending,
    issuedCredentials,
    deleteTarget,
    search,
    page,
    paged,
    totalPages,
    stats,

    setField,
    setSearch,
    setPage,
    setResendTarget,
    setDeleteTarget,

    handleSubmit,
    handleDeleteConfirm,
    handleResendConfirm,
    closeIssuedCredentials: () => {
      setIssuedCredentials(null);
    },
    handleOpenEdit,
    closeDialog,
  };
}

/** Pulls the API's message out of an RTK Query error, with a fallback. */
function readError(err: unknown, fallback: string): string {
  const data = (err as { data?: { message?: string | string[] } })?.data;
  if (Array.isArray(data?.message)) return data.message.join(", ");
  return data?.message ?? fallback;
}

/**
 * Splits a stored full name back into the form's parts. Names were composed
 * as "First [M] Last", so a lone letter (optionally with a dot) after the
 * first word is taken as the middle initial, everything before it as the
 * first name and everything after as the last. With no initial, the first
 * word is the first name and the rest the last name — wrong for a two-word
 * first name, which is why the dialog asks the coordinator to check.
 */
export function splitPersonName(name: string): {
  firstName: string;
  middleInitial: string;
  lastName: string;
} {
  const words = name.trim().split(/\s+/).filter(Boolean);
  if (words.length <= 1) {
    return { firstName: words[0] ?? "", middleInitial: "", lastName: "" };
  }
  const initialAt = words.findIndex(
    (word, i) => i > 0 && i < words.length - 1 && /^[A-Za-z]\.?$/.test(word),
  );
  if (initialAt > 0) {
    return {
      firstName: words.slice(0, initialAt).join(" "),
      middleInitial: words[initialAt],
      lastName: words.slice(initialAt + 1).join(" "),
    };
  }
  return {
    firstName: words[0],
    middleInitial: "",
    lastName: words.slice(1).join(" "),
  };
}
